services:
  jobmanager:
    image: flink:1.18.1-scala_2.12-java11
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - HADOOP_CLASSPATH=/opt/hadoop/etc/hadoop:/opt/hadoop/share/hadoop/common/lib/*:/opt/hadoop/share/hadoop/common/*:/opt/hadoop/share/hadoop/hdfs:/opt/hadoop/share/hadoop/hdfs/lib/*:/opt/hadoop/share/hadoop/hdfs/*
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 1024m
        jobmanager.memory.heap.size: 512m
        jobmanager.memory.off-heap.size: 128m
        jobmanager.memory.jvm-metaspace.size: 192m
        jobmanager.memory.jvm-overhead.min: 96m
        jobmanager.memory.jvm-overhead.max: 192m
    volumes:
      - ./jobs:/opt/flink/jobs
      - hdfs_config_shared_volume:/opt/hadoop/etc/hadoop
      - hdfs_shared_volume:/opt/hadoop/share/hadoop
    networks:
      - datatower_network

  taskmanager:
    image: flink:1.18.1-scala_2.12-java11
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - HADOOP_CLASSPATH=/opt/hadoop/etc/hadoop:/opt/hadoop/share/hadoop/common/lib/*:/opt/hadoop/share/hadoop/common/*:/opt/hadoop/share/hadoop/hdfs:/opt/hadoop/share/hadoop/hdfs/lib/*:/opt/hadoop/share/hadoop/hdfs/*
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        taskmanager.memory.process.size: 4096m
        taskmanager.memory.framework.heap.size: 256m
        taskmanager.memory.framework.off-heap.size: 256m
        taskmanager.memory.task.heap.size: 2023m
        taskmanager.memory.managed.size: 1024m
        taskmanager.memory.jvm-metaspace.size: 256m
        taskmanager.memory.network.min: 10m
        taskmanager.memory.network.max: 25m
        taskmanager.memory.jvm-overhead.min: 128m
        taskmanager.memory.jvm-overhead.max: 256m
    volumes:
      - hdfs_config_shared_volume:/opt/hadoop/etc/hadoop
      - hdfs_shared_volume:/opt/hadoop/share/hadoop
    networks:
      - datatower_network