services:
  metastore:
    image: 'apache/hive:3.1.3'
    container_name: metastore
    networks:
      - datatower_network
    depends_on:
      - mysql
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=mysql
      - HIVE_CUSTOM_CONF_DIR=/hive_custom_conf
      # uncoment before restart metastore
#      - IS_RESUME="false"
    ports:
      - "9083:9083"
    volumes:
      - hdfs_config_shared_volume:/hive_custom_conf:ro
      - ./jdbc/mysql-connector-j-8.0.33.jar:/opt/hive/lib/mysql-connector-j.jar
